---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: voip-staging
spec:
  encryptedData:
    .dockerconfigjson: AgAhf0LslK/GvR/ArA6TVnI6dVf5dsMh3ORS5STXqig4kanwYIKbAXM18XE157XCXskeAS3HHO80hTv1ZhWEpVzSyJourLhO2wWe9ZryN4A9W+MkO8XE/CVvnZaedfzqLEtZK6aZxCSxDQ/xwBl9PTLhNp9JIdY2KGV1DtZEwzYj0tfadT1zI8nQLjeVsMLGn+QoM2CMqcK8XPdIOGo30PKPKrlHiFx/Ggrlr7bVP3hkCK0Uk0A1w+KYx50ySvlNNB00bkBAXLkbSYo6a5gtvOgG+X4JMuWXgfb9B33HDOYPa74mkhWLrh8rnej2aGEJPzPlj7McWOneLcryRITLNHuzHRw52Hx0n7TgVj/D4ekcBcYWS2ceYUgWYxw0P5JG4SufEH8BJIvo91lz8/rwot3/hJbbObTkfvXH2NTZZNqEVKhcTpm3zrLGo6SlYZ1Q3OofyGeHEg8fXC9ZjssivT2Q8GTUWypKb7L/UWg0Ehcu47VUX7GEgZVR1X5mAr5i5YF3mNlT/DI7Zz1D5NpCE2lvr/XNUHvBlT7JCuPY1EDNOXZBWKjUkIsrIbJ2pGFEZ8l59y/7ROYoYYsc2sRU+10ZDDPgV5u1ahul9PIkPDWRvXLsDBzkiYv2rMZ2CgutlT8gMy8LVehehSsQLZbm1hOyGGY6LMMLCffnc0mfZiyLzhZvh426grjINegK5YIqEI7rxMEDPYXQe6ccSp6adE3lM6YUub4gdyw35/0oNN+b0krghShC4oTPiVy/XJm15+ollhpGa87Dt2qPxqCVoE8qQXPTQ3ZBWc60K+ub1AYYbUpT7FLNbM9IQZP3YxqWaZzUKh/eYRWYwpf8aZxK1JDg6owwfRdoveXe8LPFYGPqtnyMoWfDjShf/swQktOROXRYy2Y7mBCVwz7eFJq/T58OSSe9xVrLnZ1XXaV/
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: voip-staging
    type: kubernetes.io/dockerconfigjson
