---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: voip-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAz1h0qjPrBpnpL2oZhpPnLFtThRjU1NYntv71EK65iKXRG/DVqeZlVRKNYDtsx5T6FHc9hufECQ5N011muaLlnmwGJYJneSFmXDgo+dIF35LCcaObKcNzDUyk86VFc6oUenD4dM1uyUAzYYzOKiGPL18mrGGMzw74ebWISbxZdYwmTmMsdRpNVR/MaOPgcS/HRyE+S7LkXkqfNFBr5h4wySm8YAS42A9PFaOxkdXUvxsH0zo88DQ7SVvBGArFRmzHax40J27EhxYm6StTM2xXqpNuWSs+Hl20K+ojUumiHpIA4IVzU/Y5zOYbYny6K9xfbp9/QiqWow38xZtwovXKz8U5ISVmTMV1/4nUCB9BSgaBqWdQvVehbWb+2emdhTlgl9/yItkqcWmuirbQ6+RPwKDy89lT6N+hOm0d+VDj52oZgmmYINb+XKQPYySLVe1lM4e0AqauPcQvJcL4XUy09Bn7PYiY/9OxokcNvVmC7WR7L1g+agoQtf8hk9gJOjSpc9KS0zTPIOIqLPQXNtu2PxR/7sijUj57cvaMyIJJ7Txe44Ruqzm8rTq3CXWe/y5oZLkxJLXNJVi4n3hm4YmbITlHaIBP0un4DQKO4cC2QweTNrNQrRoCuPGtnRfkAl0ReEf/gJzi6b37qq5ACEvjgeCwXdPqOhXi9n7u3tE2dsfc8ZwApdO2+TqPEJi0w8JkaibrHFHpzucmdPNpTu5oJOxQZvK23IFPyr23MNxxMUBcQulcH
    POSTGRES_USER: AgA4wfVDEtLxNfJAnabeHWnbc2MKBukWMAlxl/17cwMv0+C8q4NpF5CmnqNOsU9a1A0NArAS8WzJYWry7max166tG/7ZxH7G90CdqUscm3igaCNb7JkSTIeWu/ZFo01E38RzEAWbjvVzN9OKbuZfyI7GRr9SXZhdTW9b77UH+MevNFjtdVM++4RggUuaqpbEh/DB6s8DY/enV41V80HJWmV1msaJruuIYyNSA2kPC92C0Yg5O9cZTqpdnggEzJoYSP4R/hWNLIRkr1DAJD+aAd2iJvqOGqAIz9h+wmLt10cZyCmBn6qK95SkconUtt1iYHTMOLAzT4/KvSJtHTOk52VbPs2VUYfbmBAIah4TAWTITJN3FYTqiVPThcbNesHUeAZeNHKRq+m33snKqla0dk0VIQelZ8l2adrR+gE9gDit7ICKQBNnqJMTS6zgY4KwRQoegWyjjK0SoLXr6GIyGlUFelqylNM+nprL8RprK4ldPFkt1lGS0NpaxVf8XXhEEjZDb1qZs5uw2OoZW+gR7sCQma1ZBLcykyS711uOfOIWNtZuoyI9ZRdUY+nBMqi7lnwojguDK+5lqD0kcwGsldgXpMTkVr9Lw2yixqyMCrPTOXrc9r2bS32TJM4Dr9vqurJc//48AC7LmE61MwwCBc/hsF5//mLLEiu94egK2PuhSEAcvjwbjVIieNmMW7n7mxd+6RMfyHRfVRY=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: voip-staging
