# TODO: Replace this with actual sealed secret
# 
# To create the real sealed secret, run:
# kubectl create secret generic postgres-credentials \
#   --from-literal=POSTGRES_USER=voip_user \
#   --from-literal=POSTGRES_PASSWORD='GENERATE_SECURE_PASSWORD' \
#   --from-literal=POSTGRES_HOST=smarttt-pg-rw.databases.svc.cluster.local \
#   --from-literal=POSTGRES_PORT=5432 \
#   --from-literal=POSTGRES_DB=voip \
#   --namespace=voip-staging \
#   --dry-run=client -o yaml | \
#   kubeseal -o yaml > sealed-postgres-credentials.yaml
#
# First create the database user in PostgreSQL:
# kubectl exec -n databases smarttt-pg-1 -- psql -U postgres -c "
#   CREATE USER voip_user WITH PASSWORD 'SAME_PASSWORD_AS_ABOVE';
#   CREATE DATABASE voip OWNER voip_user;
#   GRANT ALL PRIVILEGES ON DATABASE voip TO voip_user;
# "

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: voip-staging
spec:
  encryptedData:
    POSTGRES_USER: PLACEHOLDER_WILL_BE_GENERATED_BY_KUBESEAL
    POSTGRES_PASSWORD: PLACEHOLDER_WILL_BE_GENERATED_BY_KUBESEAL
    POSTGRES_HOST: PLACEHOLDER_WILL_BE_GENERATED_BY_KUBESEAL
    POSTGRES_PORT: PLACEHOLDER_WILL_BE_GENERATED_BY_KUBESEAL
    POSTGRES_DB: PLACEHOLDER_WILL_BE_GENERATED_BY_KUBESEAL
  template:
    metadata:
      name: postgres-credentials
      namespace: voip-staging
    type: Opaque
