apiVersion: apps/v1
kind: Deployment
metadata:
  name: signaling-service
spec:
  replicas: 2  # Staging uses 2 replicas for HA
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
      - name: signaling
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
